### ISSUE TITLE
ProtonVPN authentication

### ISSUE THREAD

**Issue by reinierma** [000Daniel/How-to-install-ProtonVPN-on-Arch-Linux#1]
Your scripts work flawlessly. Thanks. Possibly something to enhance. Running ProtonVPN on Endeavouros requires always authentication for accessing the VPN (password). Installing ProtonVPN on Manjaro and MXLinux does not have this. In addition, the username has to be given for the KDE wallet when starting protonVPN the first time. I'm not sure if this is something of your script or of Endeavouros.

**Comment by 000Daniel** [comment]
> Your scripts work flawlessly. Thanks. Possibly something to enhance. Running ProtonVPN on Endeavouros requires always authentication for accessing the VPN (password). Installing ProtonVPN on Manjaro and MXLinux does not have this. In addition, the username has to be given for the KDE wallet when starting protonVPN the first time. I'm not sure if this is something of your script or of Endeavouros.

Hmm... on my system(endeavour-os) I do not have 'KDE wallet' installed, it is very possible that Proton-VPN asks for it automatically to store your passwords more safely.
Also thanks for the feedback!

**Comment by reinierma** [comment]
Problems solved:
1. ~/.config/kwalletrc

[Wallet]
Enabled=false 

2. Installed Seahorse (GNOME’s Password & Encryption Key Manager) and started ProtonVPN. After entering a new password for Seahorse, the ProtonVPN login credentials were correctly stored and protonVPN runs fine.
